--2019-11-04 09:52:18--  (try: 2)  https://raw.githubusercontent.com/qiime2/environment-files/master/2018.8/release/qiime2-2018.8-py35-linux-conda.yml
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|66.220.149.32|:443... failed: Connection timed out.
Retrying.

--2019-11-04 09:54:27--  (try: 3)  https://raw.githubusercontent.com/qiime2/environment-files/master/2018.8/release/qiime2-2018.8-py35-linux-conda.yml
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|66.220.149.32|:443... failed: Connection timed out.
Retrying.

--2019-11-04 09:56:37--  (try: 4)  https://raw.githubusercontent.com/qiime2/environment-files/master/2018.8/release/qiime2-2018.8-py35-linux-conda.yml
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|66.220.149.32|:443... failed: Connection timed out.
Retrying.

--2019-11-04 09:58:49--  (try: 5)  https://raw.githubusercontent.com/qiime2/environment-files/master/2018.8/release/qiime2-2018.8-py35-linux-conda.yml
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|66.220.149.32|:443... failed: Connection timed out.
Retrying.

--2019-11-04 10:01:01--  (try: 6)  https://raw.githubusercontent.com/qiime2/environment-files/master/2018.8/release/qiime2-2018.8-py35-linux-conda.yml
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|66.220.149.32|:443... failed: Connection timed out.
Retrying.

--2019-11-04 10:03:14--  (try: 7)  https://raw.githubusercontent.com/qiime2/environment-files/master/2018.8/release/qiime2-2018.8-py35-linux-conda.yml
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|66.220.149.32|:443... failed: Connection timed out.
Retrying.

--2019-11-04 10:05:22--  (try: 8)  https://raw.githubusercontent.com/qiime2/environment-files/master/2018.8/release/qiime2-2018.8-py35-linux-conda.yml
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|66.220.149.32|:443... failed: Connection timed out.
Retrying.

--2019-11-04 10:07:37--  (try: 9)  https://raw.githubusercontent.com/qiime2/environment-files/master/2018.8/release/qiime2-2018.8-py35-linux-conda.yml
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|66.220.149.32|:443... failed: Connection timed out.
Retrying.

--2019-11-04 10:09:53--  (try:10)  https://raw.githubusercontent.com/qiime2/environment-files/master/2018.8/release/qiime2-2018.8-py35-linux-conda.yml
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|66.220.149.32|:443... failed: Connection timed out.
Retrying.

--2019-11-04 10:12:11--  (try:11)  https://raw.githubusercontent.com/qiime2/environment-files/master/2018.8/release/qiime2-2018.8-py35-linux-conda.yml
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|66.220.149.32|:443... failed: Connection timed out.
Retrying.

--2019-11-04 10:14:28--  (try:12)  https://raw.githubusercontent.com/qiime2/environment-files/master/2018.8/release/qiime2-2018.8-py35-linux-conda.yml
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|66.220.149.32|:443... failed: Connection timed out.
Retrying.

--2019-11-04 10:16:45--  (try:13)  https://raw.githubusercontent.com/qiime2/environment-files/master/2018.8/release/qiime2-2018.8-py35-linux-conda.yml
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|66.220.149.32|:443... failed: Connection timed out.
Retrying.

--2019-11-04 10:19:02--  (try:14)  https://raw.githubusercontent.com/qiime2/environment-files/master/2018.8/release/qiime2-2018.8-py35-linux-conda.yml
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|66.220.149.32|:443... failed: Connection timed out.
Retrying.

--2019-11-04 10:21:20--  (try:15)  https://raw.githubusercontent.com/qiime2/environment-files/master/2018.8/release/qiime2-2018.8-py35-linux-conda.yml
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|66.220.149.32|:443... failed: Connection timed out.
Retrying.

--2019-11-04 10:23:37--  (try:16)  https://raw.githubusercontent.com/qiime2/environment-files/master/2018.8/release/qiime2-2018.8-py35-linux-conda.yml
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|66.220.149.32|:443... failed: Connection timed out.
Retrying.

--2019-11-04 10:25:54--  (try:17)  https://raw.githubusercontent.com/qiime2/environment-files/master/2018.8/release/qiime2-2018.8-py35-linux-conda.yml
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|66.220.149.32|:443... failed: Connection timed out.
Retrying.

--2019-11-04 10:28:11--  (try:18)  https://raw.githubusercontent.com/qiime2/environment-files/master/2018.8/release/qiime2-2018.8-py35-linux-conda.yml
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|66.220.149.32|:443... failed: Connection timed out.
Retrying.

--2019-11-04 10:30:29--  (try:19)  https://raw.githubusercontent.com/qiime2/environment-files/master/2018.8/release/qiime2-2018.8-py35-linux-conda.yml
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|66.220.149.32|:443... failed: Connection timed out.
Retrying.

--2019-11-04 10:32:46--  (try:20)  https://raw.githubusercontent.com/qiime2/environment-files/master/2018.8/release/qiime2-2018.8-py35-linux-conda.yml
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|66.220.149.32|:443... failed: Connection timed out.
Giving up.

